app/models.py
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from flask_login import LoginManager


db = SQLAlchemy()
login_manager = LoginManager()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, nullable=False, index=True)
    username = db.Column(db.String(64), nullable=False, unique=True, index=True)
    password_hash = db.Column(db.String(128))
    reviews = db.relationship("Review", backref="reviewer", lazy=True)

    @property
    def password(self):
        raise AttributeError("Password is not a readable property")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


class Book(db.Model):
    __tablename__ = "books"
    id = db.Column(db.Integer, primary_key=True)
    isbn = db.Column(db.String(64), nullable=False)
    title = db.Column(db.String(128), nullable=False)
    author = db.Column(db.String(256), nullable=False)
    year = db.Column(db.Integer, nullable=False)
    reviews = db.relationship("Review", backref="book", lazy=True)


class Review(db.Model):
    __tablename__ = "reviews"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    book_id = db.Column(db.Integer, db.ForeignKey("books.id"), nullable=False)
    username = db.Column(db.String(64), nullable=False)
    book_title = db.Column(db.String(128), nullable=False)
    book_isbn = db.Column(db.String(128), nullable=False)
    review = db.Column(db.String, nullable=False)

app/__init__.py
import os

from flask import Flask, session
from flask_bootstrap import Bootstrap
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy

from config import Config
from .models import db, login_manager


app = Flask(__name__)
app.config.from_object(Config)
db.init_app(app)
login_manager.init_app(app)

if not os.getenv("DATABASE_URL"):
    raise RuntimeError("DATABASE_URL is not set!!")

bootstrap = Bootstrap(app)


from .main import main as main_blueprint
app.register_blueprint(main_blueprint)

from .auth import auth as auth_blueprint
app.register_blueprint(auth_blueprint)

from .apis import api as api_blueprint
app.register_blueprint(api_blueprint)

app/apis/__init__.py
from app.apis.goodreads import get_isbn_data
from flask import Blueprint


api = Blueprint('api', __name__)

from app.apis import views

app/apis/views.py
from . import api
from app.models import Book, Review
from flask import jsonify


@api.route("/api/<string:isbn>")
def send_book_data(isbn):
    book = Book.query.filter_by(isbn=isbn).first()
    if book:
        json_file = {}
        json_file["title"] = book.title
        json_file["author"] = book.author
        json_file["year"] = book.year
        json_file["isbn"] = book.isbn
        json_file["review_count"] = Review.query.filter_by(book_id=book.id).count()

    return jsonify(json_file)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import views

app/main/views.py
from flask import render_template, request, redirect, url_for
from flask_login import login_required, current_user
from . import main
from app.models import Book, User, Review
from app import db
from app.apis import get_isbn_data


@main.route("/")
def index():
    return render_template("auth/login.html")


@main.route("/user/<string:username>")
@login_required
def user(username):
    user_ = User.query.filter_by(username=username).first()
    if user_:
        if current_user.id == user_.id:
            return render_template("main/user.html", user=user_)
        else:
            return render_template("error.html", message="User is not logged-in please log-in")
    else:
        return render_template("error.html", message="User does not exists!")


@main.route("/search", methods=['POST'])
@login_required
def search():
    isbn_code = request.form.get("bookisbn")
    if isbn_code:
        book = Book.query.filter_by(isbn=isbn_code).first()
        if book:
            return redirect(url_for('main.bookpage', isbn=book.isbn))
    return render_template("main/user.html", username=current_user)


@main.route("/book/<string:isbn>")
@login_required
def bookpage(isbn):
    book = Book.query.filter_by(isbn=isbn).first()
    if book is None:
        return render_template("error.html", message="Book does not exists")

    goodreads_info = get_isbn_data(isbn)
    reviews = Review.query.all()
    return render_template("main/book.html", book=book, reviews=reviews, goodreads_info=goodreads_info)


@main.route("/allbooks")
def allbooks():
    books = Book.query.order_by(Book.title.asc()).all()
    return render_template("main/allbooks.html", books=books)


@main.route("/addreview/<string:isbn>", methods=['POST'])
@login_required
def add_review(isbn):
    comment = request.form.get("comment")
    if comment.isspace():
        return render_template("error.html", message="You should write a string")

    # Adding the review
    book = Book.query.filter_by(isbn=isbn).first()
    if book is None:
        return render_template("error.html", message="The book isbn does not exist!")

    user_id = current_user.id
    book_id = book.id
    username = current_user.username
    book_title = book.title
    book_isbn = book.isbn

    review = Review(user_id=user_id, book_id=book_id, username=username,
                    book_title=book_title, book_isbn=book_isbn, review=comment)

    db.session.add(review)
    db.session.commit()
    reviews = Review.query.all()
    goodreads_info = get_isbn_data(book_isbn)
    return render_template("main/book.html", reviews=reviews, book=book, goodreads_info=goodreads_info)


@main.route("/remove_review/<int:review_id>")
def remove_review(review_id):
    review = Review.query.filter_by(id=review_id).first()
    book = Book.query.filter_by(isbn=review.book_isbn)
    if review:
        Review.query.filter_by(id=review_id).delete()
        db.session.commit()
    goodreads_info = get_isbn_data(book.isbn)
    reviews = Review.query.all()
    return render_template("main/book.html", reviews=reviews, book=book, goodreads_info=goodreads_info)


@main.route("/userprofile/<string:username>")
def profile(username):
    user_ = User.query.filter_by(username=username).first()
    if user_:
        return render_template("main/profile.html", userprofile=user_)

    return render_template("error.html", message="User does not exist")

app/templates/error.html
{% extends "layout.html" %}

{% block head %}
    <title>Error!</title>
{% endblock %}

{% block body %}
    <h1>{{ message }}</h1>
    <a href="{{ url_for('main.index') }}">Back to login</a>
{% endblock %}

app/templates/in_construction.html
{% extends "layout.html" %}

{% block head %}
<title>Debugging webpage</title>
{% endblock %}

{% block body %}
    <h1>{{ message }}</h1>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}
</head>
<body>
{% block navbar %}
{% endblock %}
{% block body %}
{% endblock %}
</body>
</html>

app/templates/main/allbooks.html
{% extends "layout.html" %}

{% block head %}
    <title>All our our books</title>
{% endblock %}

{% block navbar %}
    <a href="{{ url_for('main.user', username=current_user.username) }}">Back to home</a>
{% endblock %}

{% block body %}
    <ol>
        {% for book in books %}
            <li><a href="{{ url_for('main.bookpage', isbn=book.isbn) }}">{{ book.title }}, {{ book.year }}</a></li>
        {% endfor %}
    </ol>
{% endblock %}

app/templates/main/book.html
{% extends "layout.html" %}

{% block head %}
    <title>{{ book.title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='main/book.css') }}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="{{ url_for('static', filename='main/book.js') }}"></script>
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.user', username=current_user.username) }}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.allbooks') }}">List all books in stock</a>
          </li>
        </ul>
      </div>
    </nav>
{% endblock %}

{% block body %}
    <h1>Web page for book {{ book.title }}</h1>
    <ul>
        <li>Author: {{ book.author }}</li>
        <li>Year published: {{ book.year }}</li>
        <li>ISBN: {{ book.isbn }}</li>
        {% if goodreads_info.status_code == 200 %}
            <li>Goodreads number of ratings: {{ goodreads_info.json().books[0].ratings_count }}</li>
            <li>Goodreads average rating: {{ goodreads_info.json().books[0].average_rating }}</li>
        {% endif %}
    </ul>

    <!-- Review Creation Section -->
        <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Demo</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

        <!-- Leave Review Box -->
        <div class="row" style="margin-top:40px;">
            <div class="col-md-6">
            <div class="well well-sm">
                <div class="text-right">
                    <a class="btn btn-success btn-green" href="#reviews-anchor" id="open-review-box">Leave a Review</a>
                </div>

                <div class="row" id="post-review-box" style="display:none;">
                    <div class="col-md-12">
                        <form accept-charset="UTF-8" action="{{ url_for('main.add_review', isbn=book.isbn) }}" method="post">
                            <input id="ratings-hidden" name="rating" type="hidden">
                            <textarea class="form-control animated" cols="50" id="new-review" name="comment" placeholder="Enter your review here..." rows="5"></textarea>

                            <div class="text-right">
                                <div class="stars starrr" data-rating="0"></div>
                                <a class="btn btn-danger btn-sm" href="#" id="close-review-box" style="display:none; margin-right: 10px;">
                                <span class="glyphicon glyphicon-remove"></span>Cancel</a>
                                <button class="btn btn-success btn-lg" type="submit">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            </div>
        </div>


        <!-- Review Written box -->
		<div class="row">
			<div class="col-sm-3">
				<div class="rating-block">
					<h4>Average user rating</h4>
					<h2 class="bold padding-bottom-7">4.3 <small>/ 5</small></h2>
					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
				</div>
			</div>
			<div class="col-sm-3">
				<h4>Rating breakdown</h4>
				<div class="pull-left">
					<div class="pull-left" style="width:35px; line-height:1;">
						<div style="height:9px; margin:5px 0;">5 <span class="glyphicon glyphicon-star"></span></div>
					</div>
					<div class="pull-left" style="width:180px;">
						<div class="progress" style="height:9px; margin:8px 0;">
						  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="5" style="width: 1000%">
							<span class="sr-only">80% Complete (danger)</span>
						  </div>
						</div>
					</div>
					<div class="pull-right" style="margin-left:10px;">1</div>
				</div>
				<div class="pull-left">
					<div class="pull-left" style="width:35px; line-height:1;">
						<div style="height:9px; margin:5px 0;">4 <span class="glyphicon glyphicon-star"></span></div>
					</div>
					<div class="pull-left" style="width:180px;">
						<div class="progress" style="height:9px; margin:8px 0;">
						  <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="5" style="width: 80%">
							<span class="sr-only">80% Complete (danger)</span>
						  </div>
						</div>
					</div>
					<div class="pull-right" style="margin-left:10px;">1</div>
				</div>
				<div class="pull-left">
					<div class="pull-left" style="width:35px; line-height:1;">
						<div style="height:9px; margin:5px 0;">3 <span class="glyphicon glyphicon-star"></span></div>
					</div>
					<div class="pull-left" style="width:180px;">
						<div class="progress" style="height:9px; margin:8px 0;">
						  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="5" style="width: 60%">
							<span class="sr-only">80% Complete (danger)</span>
						  </div>
						</div>
					</div>
					<div class="pull-right" style="margin-left:10px;">0</div>
				</div>
				<div class="pull-left">
					<div class="pull-left" style="width:35px; line-height:1;">
						<div style="height:9px; margin:5px 0;">2 <span class="glyphicon glyphicon-star"></span></div>
					</div>
					<div class="pull-left" style="width:180px;">
						<div class="progress" style="height:9px; margin:8px 0;">
						  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="5" style="width: 40%">
							<span class="sr-only">80% Complete (danger)</span>
						  </div>
						</div>
					</div>
					<div class="pull-right" style="margin-left:10px;">0</div>
				</div>
				<div class="pull-left">
					<div class="pull-left" style="width:35px; line-height:1;">
						<div style="height:9px; margin:5px 0;">1 <span class="glyphicon glyphicon-star"></span></div>
					</div>
					<div class="pull-left" style="width:180px;">
						<div class="progress" style="height:9px; margin:8px 0;">
						  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="5" style="width: 20%">
							<span class="sr-only">80% Complete (danger)</span>
						  </div>
						</div>
					</div>
					<div class="pull-right" style="margin-left:10px;">0</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-7">
				<hr/>
                {% for review in reviews %}
                    <div class="review-block">
                        <div class="row">
                            <div class="col-sm-3">
                                <img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image" class="img-rounded">
                                {% if review.user_id == current_user.user_id %}
                                    <div class="review-block-name"><a href="{{ url_for("main.user", username=review.username) }}">{{ review.username }}</a></div>
                                {% else %}
                                    <div class="review-block-name"><a href="{{ url_for("main.profile", username=review.username) }}">{{ review.username }}</a></div>
                                {% endif %}

                            </div>
                            <div class="col-sm-9">
                                <div class="review-block-rate">
                                    <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
                                      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                                    </button>
                                    <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
                                      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                                    </button>
                                    <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
                                      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                                    </button>
                                    <button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
                                      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                                    </button>
                                    <button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
                                      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                                    </button>
                                </div>
                                <div class="review-block-description">{{ review.review }}</div>
                            </div>
                            <form action="{{ url_for('main.remove_review', review_id=review.id) }}">
                                {% if current_user.username == review.username %}
                                    <button>Delete comment!</button>
                                {% endif %}

                            </form>
                        </div>
                        <hr/>
                    </div>
                {% endfor %}
			</div>
		</div>

    </div> <!-- /container -->
{% endblock %}

app/templates/main/index.html
{% extends "layout.html" %}

{% block head %}
    <title>Welcome to Rate My Book!</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main/index.css') }}">
{% endblock %}
{% block body %}
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="username">

					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?
                    <a href="{{ url_for("auth.signup") }}">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/main/profile.html
{% extends "layout.html" %}

{% block title %}
<title> {{ userprofile.username }} Profile!</title>
{% endblock %}

{% block body %}
    {% if current_user.is_authenticated %}
        <a href="{{ url_for('main.user', username=current_user.username) }}">Home</a>
    {% else %}
        <a href="{{ url_for('main.index') }}">Home</a>
    {% endif %}
    <h1> Hello to {{ userprofile.username }}'s Personal Profile!</h1
{% endblock %}

app/templates/main/user.html
{% extends "layout.html" %}

{% block head %}
    <title>Book Reviews For {{ user.username }}</title>
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main.user', username=current_user.username) }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="navbar-link" href="{{ url_for('main.allbooks') }}">List all books</a>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block body %}
    <h1>Welcome {{ user.username }}!</h1>
    <!-- Search form -->
    <form action="{{ url_for('main.search') }}" method="post">
        <div class="active-pink-3 active-pink-4 mb-4">
          <input class="form-control" type="text" placeholder="Book Name" aria-label="Search" name="bookname">
        </div>
        <div class="active-pink-3 active-pink-4 mb-4">
            <input class="form-control" type="text" placeholder="Author" aria-label="Search" name="bookauthor">
        </div>
        <div class="active-pink-3 active-pink-4 mb-4">
            <input class="form-control" type="text" placeholder="isbn" aria-label="Search" name="bookisbn">
        </div>
        <div class="btn-primary">
            <button>Search!</button>
        </div>
    </form>
{% endblock %}